version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: news
    ports:
      - 5432:5432
    volumes:
      - ./modules/core/src/main/resources/sql:/docker-entrypoint-initdb.d/
